server: stewartia.forestry.oregonstate.edu:1433
user: petersonf
password: D0ntd1sATLGA!!
database: FSDBDATA

f: problem_trees3.log
inventory_file: years_stands_remeasured.yaml
query_file: qf_2.yaml
dead_inventory_plot: all_dead_only.yaml
total_inventory_plot: all_live_and_dead.yaml
dead_inventory_stand: all_dead_only_standscale.yaml
total_inventory_stand: all_live_and_dead_standscale.yaml

litedb: areas.db
litetable: plotAreas